# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sitec-work/Desktop/final_st

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sitec-work/Desktop/final_st

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sitec-work/Desktop/final_st/CMakeFiles /home/sitec-work/Desktop/final_st/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sitec-work/Desktop/final_st/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named seam_track_v2

# Build rule for target.
seam_track_v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 seam_track_v2
.PHONY : seam_track_v2

# fast build rule for target.
seam_track_v2/fast:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/build
.PHONY : seam_track_v2/fast

archives/dependencies/lib/egm.pb.o: archives/dependencies/lib/egm.pb.cc.o

.PHONY : archives/dependencies/lib/egm.pb.o

# target to build an object file
archives/dependencies/lib/egm.pb.cc.o:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/archives/dependencies/lib/egm.pb.cc.o
.PHONY : archives/dependencies/lib/egm.pb.cc.o

archives/dependencies/lib/egm.pb.i: archives/dependencies/lib/egm.pb.cc.i

.PHONY : archives/dependencies/lib/egm.pb.i

# target to preprocess a source file
archives/dependencies/lib/egm.pb.cc.i:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/archives/dependencies/lib/egm.pb.cc.i
.PHONY : archives/dependencies/lib/egm.pb.cc.i

archives/dependencies/lib/egm.pb.s: archives/dependencies/lib/egm.pb.cc.s

.PHONY : archives/dependencies/lib/egm.pb.s

# target to generate assembly for a file
archives/dependencies/lib/egm.pb.cc.s:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/archives/dependencies/lib/egm.pb.cc.s
.PHONY : archives/dependencies/lib/egm.pb.cc.s

archives/dependencies/lib/xiApiPlusOcv.o: archives/dependencies/lib/xiApiPlusOcv.cpp.o

.PHONY : archives/dependencies/lib/xiApiPlusOcv.o

# target to build an object file
archives/dependencies/lib/xiApiPlusOcv.cpp.o:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/archives/dependencies/lib/xiApiPlusOcv.cpp.o
.PHONY : archives/dependencies/lib/xiApiPlusOcv.cpp.o

archives/dependencies/lib/xiApiPlusOcv.i: archives/dependencies/lib/xiApiPlusOcv.cpp.i

.PHONY : archives/dependencies/lib/xiApiPlusOcv.i

# target to preprocess a source file
archives/dependencies/lib/xiApiPlusOcv.cpp.i:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/archives/dependencies/lib/xiApiPlusOcv.cpp.i
.PHONY : archives/dependencies/lib/xiApiPlusOcv.cpp.i

archives/dependencies/lib/xiApiPlusOcv.s: archives/dependencies/lib/xiApiPlusOcv.cpp.s

.PHONY : archives/dependencies/lib/xiApiPlusOcv.s

# target to generate assembly for a file
archives/dependencies/lib/xiApiPlusOcv.cpp.s:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/archives/dependencies/lib/xiApiPlusOcv.cpp.s
.PHONY : archives/dependencies/lib/xiApiPlusOcv.cpp.s

common/common.o: common/common.cpp.o

.PHONY : common/common.o

# target to build an object file
common/common.cpp.o:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/common/common.cpp.o
.PHONY : common/common.cpp.o

common/common.i: common/common.cpp.i

.PHONY : common/common.i

# target to preprocess a source file
common/common.cpp.i:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/common/common.cpp.i
.PHONY : common/common.cpp.i

common/common.s: common/common.cpp.s

.PHONY : common/common.s

# target to generate assembly for a file
common/common.cpp.s:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/common/common.cpp.s
.PHONY : common/common.cpp.s

common/pthread_creator.o: common/pthread_creator.cpp.o

.PHONY : common/pthread_creator.o

# target to build an object file
common/pthread_creator.cpp.o:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/common/pthread_creator.cpp.o
.PHONY : common/pthread_creator.cpp.o

common/pthread_creator.i: common/pthread_creator.cpp.i

.PHONY : common/pthread_creator.i

# target to preprocess a source file
common/pthread_creator.cpp.i:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/common/pthread_creator.cpp.i
.PHONY : common/pthread_creator.cpp.i

common/pthread_creator.s: common/pthread_creator.cpp.s

.PHONY : common/pthread_creator.s

# target to generate assembly for a file
common/pthread_creator.cpp.s:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/common/pthread_creator.cpp.s
.PHONY : common/pthread_creator.cpp.s

egm_sensor.o: egm_sensor.cpp.o

.PHONY : egm_sensor.o

# target to build an object file
egm_sensor.cpp.o:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/egm_sensor.cpp.o
.PHONY : egm_sensor.cpp.o

egm_sensor.i: egm_sensor.cpp.i

.PHONY : egm_sensor.i

# target to preprocess a source file
egm_sensor.cpp.i:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/egm_sensor.cpp.i
.PHONY : egm_sensor.cpp.i

egm_sensor.s: egm_sensor.cpp.s

.PHONY : egm_sensor.s

# target to generate assembly for a file
egm_sensor.cpp.s:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/egm_sensor.cpp.s
.PHONY : egm_sensor.cpp.s

grey_alg.o: grey_alg.cpp.o

.PHONY : grey_alg.o

# target to build an object file
grey_alg.cpp.o:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/grey_alg.cpp.o
.PHONY : grey_alg.cpp.o

grey_alg.i: grey_alg.cpp.i

.PHONY : grey_alg.i

# target to preprocess a source file
grey_alg.cpp.i:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/grey_alg.cpp.i
.PHONY : grey_alg.cpp.i

grey_alg.s: grey_alg.cpp.s

.PHONY : grey_alg.s

# target to generate assembly for a file
grey_alg.cpp.s:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/grey_alg.cpp.s
.PHONY : grey_alg.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/main.cpp.s
.PHONY : main.cpp.s

pid_controller.o: pid_controller.cpp.o

.PHONY : pid_controller.o

# target to build an object file
pid_controller.cpp.o:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/pid_controller.cpp.o
.PHONY : pid_controller.cpp.o

pid_controller.i: pid_controller.cpp.i

.PHONY : pid_controller.i

# target to preprocess a source file
pid_controller.cpp.i:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/pid_controller.cpp.i
.PHONY : pid_controller.cpp.i

pid_controller.s: pid_controller.cpp.s

.PHONY : pid_controller.s

# target to generate assembly for a file
pid_controller.cpp.s:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/pid_controller.cpp.s
.PHONY : pid_controller.cpp.s

udp_server.o: udp_server.cpp.o

.PHONY : udp_server.o

# target to build an object file
udp_server.cpp.o:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/udp_server.cpp.o
.PHONY : udp_server.cpp.o

udp_server.i: udp_server.cpp.i

.PHONY : udp_server.i

# target to preprocess a source file
udp_server.cpp.i:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/udp_server.cpp.i
.PHONY : udp_server.cpp.i

udp_server.s: udp_server.cpp.s

.PHONY : udp_server.s

# target to generate assembly for a file
udp_server.cpp.s:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/udp_server.cpp.s
.PHONY : udp_server.cpp.s

wobble_controller.o: wobble_controller.cpp.o

.PHONY : wobble_controller.o

# target to build an object file
wobble_controller.cpp.o:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/wobble_controller.cpp.o
.PHONY : wobble_controller.cpp.o

wobble_controller.i: wobble_controller.cpp.i

.PHONY : wobble_controller.i

# target to preprocess a source file
wobble_controller.cpp.i:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/wobble_controller.cpp.i
.PHONY : wobble_controller.cpp.i

wobble_controller.s: wobble_controller.cpp.s

.PHONY : wobble_controller.s

# target to generate assembly for a file
wobble_controller.cpp.s:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/wobble_controller.cpp.s
.PHONY : wobble_controller.cpp.s

ximea_camera.o: ximea_camera.cpp.o

.PHONY : ximea_camera.o

# target to build an object file
ximea_camera.cpp.o:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/ximea_camera.cpp.o
.PHONY : ximea_camera.cpp.o

ximea_camera.i: ximea_camera.cpp.i

.PHONY : ximea_camera.i

# target to preprocess a source file
ximea_camera.cpp.i:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/ximea_camera.cpp.i
.PHONY : ximea_camera.cpp.i

ximea_camera.s: ximea_camera.cpp.s

.PHONY : ximea_camera.s

# target to generate assembly for a file
ximea_camera.cpp.s:
	$(MAKE) -f CMakeFiles/seam_track_v2.dir/build.make CMakeFiles/seam_track_v2.dir/ximea_camera.cpp.s
.PHONY : ximea_camera.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... seam_track_v2"
	@echo "... archives/dependencies/lib/egm.pb.o"
	@echo "... archives/dependencies/lib/egm.pb.i"
	@echo "... archives/dependencies/lib/egm.pb.s"
	@echo "... archives/dependencies/lib/xiApiPlusOcv.o"
	@echo "... archives/dependencies/lib/xiApiPlusOcv.i"
	@echo "... archives/dependencies/lib/xiApiPlusOcv.s"
	@echo "... common/common.o"
	@echo "... common/common.i"
	@echo "... common/common.s"
	@echo "... common/pthread_creator.o"
	@echo "... common/pthread_creator.i"
	@echo "... common/pthread_creator.s"
	@echo "... egm_sensor.o"
	@echo "... egm_sensor.i"
	@echo "... egm_sensor.s"
	@echo "... grey_alg.o"
	@echo "... grey_alg.i"
	@echo "... grey_alg.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pid_controller.o"
	@echo "... pid_controller.i"
	@echo "... pid_controller.s"
	@echo "... udp_server.o"
	@echo "... udp_server.i"
	@echo "... udp_server.s"
	@echo "... wobble_controller.o"
	@echo "... wobble_controller.i"
	@echo "... wobble_controller.s"
	@echo "... ximea_camera.o"
	@echo "... ximea_camera.i"
	@echo "... ximea_camera.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

